version: '3.8'

services:
    web:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - .:/var/www
        environment:
            DATABASE_URL: mysql://user:password@db:3306/healthconnect
        depends_on:
            db:
                condition: service_started
        healthcheck:
            test: ["CMD-SHELL", "ss -tlnp | grep 9000 || exit 1"]
            interval: 10s
            retries: 3
            start_period: 10s

    db:
        image: mysql:8.0
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: healthconnect
            MYSQL_USER: user
            MYSQL_PASSWORD: password
        ports:
            - "3306:3306"
        volumes:
            - db_data:/var/lib/mysql

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - "8080:80"
        environment:
            PMA_HOST: db
            MYSQL_ROOT_PASSWORD: root
        depends_on:
            - db

    nginx:
        build:
            context: ./docker/nginx
            dockerfile: Dockerfile
        ports:
            - "8000:80"
        volumes:
            - .:/var/www
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - web
        command: >
            /bin/bash -c "
              dockerize -wait tcp://web:9000 -timeout 60s
              nginx -g 'daemon off;'
            "

volumes:
    db_data:

networks:
    app-network:
        driver: bridge
